-- 제품 테이블 생성
CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  sub_category TEXT NOT NULL CHECK (sub_category IN ('Private', 'Public')),
  size_category TEXT NOT NULL CHECK (size_category IN ('S', 'M', 'L', 'XL', 'SOLUTION', 'DESIGN')),
  image_url TEXT NOT NULL,
  tagline TEXT NOT NULL,
  description TEXT NOT NULL,
  price TEXT,
  structure TEXT,
  roof_type TEXT,
  exterior_finish TEXT,
  interior_finish TEXT,
  size TEXT,
  display_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  is_signature BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_products_size_category ON products(size_category);
CREATE INDEX IF NOT EXISTS idx_products_sub_category ON products(sub_category);
CREATE INDEX IF NOT EXISTS idx_products_display_order ON products(display_order);
CREATE INDEX IF NOT EXISTS idx_products_is_active ON products(is_active);

-- updated_at 자동 업데이트 트리거
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- RLS (Row Level Security) 활성화
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- 읽기는 모든 사용자 허용 (공개 데이터)
CREATE POLICY "Anyone can view products" ON products
  FOR SELECT USING (is_active = true);

-- 수정/삭제는 인증된 사용자만 (관리자용)
CREATE POLICY "Authenticated users can insert products" ON products
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update products" ON products
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can delete products" ON products
  FOR DELETE TO authenticated USING (true);

-- 문의(Inquiries) 테이블 생성
CREATE TABLE IF NOT EXISTS inquiries (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  email text not null,
  phone text,
  message text not null,
  status text default 'new' check (status in ('new', 'read', 'replied')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 문의 테이블 RLS
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

-- 누구나 문의 등록 가능 (Public Insert)
CREATE POLICY "Anyone can insert inquiries" ON inquiries
  FOR INSERT WITH CHECK (true);

-- 관리자만 조회/수정/삭제 가능
CREATE POLICY "Authenticated users can view inquiries" ON inquiries
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can update inquiries" ON inquiries
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can delete inquiries" ON inquiries
  FOR DELETE TO authenticated USING (true);

-- FAQ 테이블 생성
CREATE TABLE IF NOT EXISTS faqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_ko TEXT NOT NULL,
  answer_ko TEXT NOT NULL,
  question_en TEXT,
  answer_en TEXT,
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- FAQ RLS
ALTER TABLE faqs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view faqs" ON faqs
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can manage faqs" ON faqs
  FOR ALL TO authenticated USING (true);

-- Inquiries 테이블 컬럼 추가 (Safe Migration)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'inquiries' AND column_name = 'category') THEN
        ALTER TABLE inquiries ADD COLUMN category TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'inquiries' AND column_name = 'reply_content') THEN
        ALTER TABLE inquiries ADD COLUMN reply_content TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'inquiries' AND column_name = 'replied_at') THEN
        ALTER TABLE inquiries ADD COLUMN replied_at TIMESTAMPTZ;
    END IF;
END $$;
