export const COMPANY = {
  name: '주식회사 위트(weet)',
  nameShort: '위트',
  phone: '010-9645-2348',
  phoneHref: 'tel:010-9645-2348',
  email: 'contact@we-et.com',
  emailHref: 'mailto:contact@we-et.com',
  address: '전남 함평군 대동면 금산길 205-27',
  addressShort: '함평군 대동면 금산길 205-27',
  businessNumber: '660-86-01862',
  instagram: 'https://www.instagram.com/weet_kr/',
  blog: 'https://blog.naver.com/we-et',
  daangn: 'https://www.daangn.com/kr/local-profile/위트weet-kihpx4ctggn6/',
  url: 'https://www.we-et.com',
} as const;
